[project]
name = 'Blockchain-Based-Hotel-Revenue-Management'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.inventory-allocation]
path = 'contracts/inventory-allocation.clar'
clarity_version = 2
epoch = 2.5

[contracts.performance-tracking]
path = 'contracts/performance-tracking.clar'
clarity_version = 2
epoch = 2.5

[contracts.property-verification]
path = 'contracts/property-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
